services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    networks:
      - spring
    ports:
      - 9411:9411

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: rabbitmq
    networks:
      - spring

    ports:
      - "5672:5672"
      - "15672:15672"

#  eureka-server:
#    image: tsud0dog/eureka-server:latest
#    container_name: eureka-server
#    ports:
#      - "8761:8761"
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker

#  apigw:
#    image: tsud0dog/apigw:latest
#    container_name: apigw
#    ports:
#      - "8083:8083"
#    networks:
#      - spring
#    depends_on:
#      - zipkin
#      - eureka-server
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker

  customer:
    image: tsud0dog/customer
    container_name: customer
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - zipkin
      - rabbitmq
    networks:
      - postgres
      - spring
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  fraud:
    image: tsud0dog/fraud
    container_name: fraud
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - zipkin
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  notification:
    image: tsud0dog/notification
    container_name: notification
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - rabbitmq
      - zipkin
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker


networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
  pgadmin: